### ISSUE TITLE
재성 - 콘텐츠 재구성하기.

### ISSUE THREAD

**Issue by blackturtle2** [joeseonmi/SOS#13]
https://docs.google.com/document/d/1RNuNSkxeNJJcogogeiSP6ep4hjirml8qfMIfkCHq9_8/edit#

일단, 2번/3번 질문 2가지를 저 나름대로 보완해봤어요.
평소 말 할 때처럼.. 쭉 쓰기 전에 말하고 싶은 질문을 먼저 제목처럼 써두고 시작하니, 키보드 칠 맛이 좀 났어요. ⌨️ 
그래도 그냥 정리하는 것보다 시간이 더 걸리는 것 같기도 하고..
두 질문들이 만만치 않은 주제여서 더 신경이 쓰이네요. ~올리고 틀린 거 없나 두고두고 볼 것 같은.. 의도치 않은 기획 의도?~

제 것만 유독히 내용이 좀 긴데.. ~짝궁님께 듣는 별명이 설명충........~
한번 두분의 컨펌 부탁드립니당. ✏️  @fimuxd @joeseonmi 

여담으로 마크다운 문법을 지원하는 `UILabel` 오픈소스를 찾아볼게요. ~제가 필요해요..~

**Comment by joeseonmi** [comment]
재성님 이야기는 동화듣는기분이라 쉽고 재밌어여ㅋㅋㅋㅋㅋ

**Comment by blackturtle2** [comment]
요 이슈는 완료 되었으므로 클로즈!
