### ISSUE TITLE
재성 - 마크다운 문법 지원 오픈소스 찾아보기

### ISSUE THREAD

**Issue by blackturtle2** [joeseonmi/SOS#17]
오픈소스 찾아서 프로토타입 만들어 보고, 적용 가능 여부 고민해 볼게요.

**Comment by blackturtle2** [comment]
// 마크다운 오픈소스를 찾으면, 거의 `WebView`나 `UITextView`로 표현하는 것들이 주로 나옵니다. 더 많은 리서치가 필요해요.

# kristopherjohnson/Markingbird

1. https://github.com/kristopherjohnson/Markingbird
2. Swift 바닥에서 가장 유명한 것으로 보이는 마크다운 프로세서.
3. 왠만한 오픈소스들은 `WebView`로 표현하고 있다. 마크다운 자체가 HTML 문법이기 때문. (...)

# initWithFunk/ by Eric Allam

1. http://initwithfunk.com/blog/2013/09/29/easy-markdown-rendering-with-nsattributedstring-on-ios-7/
2. `NSAttributedString`을 이용해 `UITextView`에 마크다운을 표현할 수 있다.
3. UILabel을 찾아보자..

# SimpleMarkdownParser on CocoaPods.org

1. https://cocoapods.org/pods/SimpleMarkdownParser
2. https://github.com/crescentflare/SimpleMarkdownParser
3. 클론 떠서 샘플 앱을 돌려볼 수 있고, 드디어 찾던 `UILabel`로 만들어진 프로젝트 !!!

**Comment by blackturtle2** [comment]
# 오늘 한일

어찌어찌 샘플까지는 돌려봤고, 소스 분석 중인데.. 음.. 그냥 임포트하고 쓰려고 했더니, 만만치 않네요.
`WebView`로 뿌려버리면 간단한 일인데, `UILabel`에 뿌리려고 해보니, 쉽지는 않습니다.
내일 조금 더 해보고, 아니다 싶으면 우리끼리 약속 정해서(별표와 별표 사이는 `Bold`체 표시 등) `UILabel`에 뿌리는 게 낫겠다 싶기도 하네요. ~사실 그렇게 크리티컬한 사항도 아니지만..~

### 샘플 앱 스크린샷
<img src="https://user-images.githubusercontent.com/28520038/30374840-4a672e00-98c1-11e7-8ed3-4bad2cfc6bc0.png" width="350">

**Comment by joeseonmi** [comment]
웹뷰로 뿌리려면 따로 웹...을 만들어야되는거죵??
확실히 md를 편하게 넣을수 있으면... 우리 팀에 md장인이 두분(...)이기때문에 편할것같은데@_@
고생하셨어여 오늘도!!!!!!!!!!!

**Comment by blackturtle2** [comment]
최종 결론(?)입니다. ~괜히 여기서 너무 시간을 끌었어..ㅠ~

## 사용한 오픈소스
아래 링크의 오픈소스를 사용하면 될 것 같습니다.
> [SimpleMarkdownParser](https://github.com/crescentflare/SimpleMarkdownParser)

## 결과적으로 가능한 마크다운 디자인(?)
결과적으로 `UILabel`에 볼드체, 취소선, 링크, 목록형(숫자, 별표)까지 표현 가능합니다.
소스코드(`hello`) 표현은 불가능하고, 굳이 필요하다면, 커스터마이징하면 될 것 같아요. ( 이것까지는 시간이 조금 걸릴 것 같.. )

|   |
|---|
|<img src="https://user-images.githubusercontent.com/28520038/30479112-b80642c8-9a4e-11e7-95d5-9787df5c45f2.png" width="350">|

## 구현 방법
`UILabel`에 `attributedText`를 사용하여 구현하는 방식입니다.
실제 사용 자체는 간단한 편이고, 구현 방식은 좀 복잡하지만, 약간의 커스터마이징은 가능할 것 같아요.
아래 소스 참고해주세요.
> [testSimpleMarkdownParser.swift](https://gist.github.com/blackturtle2/dd14a1f50a131fec9d400850169090ff)

다 같이 이 오픈소스를 사용할 것인지 결정이 필요해서 PR은 하지 않았습니다.
소스 한번 보고, 댓글 부탁드려요. 🙏  @fimuxd @joeseonmi

**Comment by joeseonmi** [comment]
저는 따로 마크다운오픈소스를 찾아보지않아서 
재성님이 고르신걸쓰는걸로하겠슴니다!!
그럼 처음JSON을 만들때 마크다운문법대로 만들면
말풍에 그대로 뿌려지는거죠? 역시 데이터만드는게 일...이겠네여ㅋㅋㅋ

**Comment by blackturtle2** [comment]
제 생각에 볼드체와 취소선, 목록 정도가 쓸만해 보여요.
보영님도 오케이하시면, pod에 넣어서 PR 하겠습니다. 😆

**Comment by blackturtle2** [comment]
dev에 PR 예정입니다.

**Comment by blackturtle2** [comment]
PR #30 과 연결됩니다. 리뷰 완료되면, 클로즈하겠습니다~ ✅

**Comment by blackturtle2** [comment]
머지 되었으므로 이 이슈는 클로즈하겠숩니다. 🥇
