### ISSUE TITLE
보영 - 개발자 소개 View 만들기

### ISSUE THREAD

**Issue by fimuxd** [joeseonmi/SOS#26]

**Comment by fimuxd** [comment]
디자인은 입히지 않고 단순 segue 연결이 가능하도록 default 형태 구현 완료

**Comment by fimuxd** [comment]
![screen shot 2017-09-21 at 12 08 57 am](https://user-images.githubusercontent.com/27915244/30651570-167fe4ba-9e61-11e7-9157-8f43fc12f5e1.png)

왠지 제가 이슈를 클로즈하면 안될 것 같아서 다시 열었습니다.
소개창은 이정도입니다.

**Comment by blackturtle2** [comment]
넹넹, 아직 닫지는 마시고, 이슈 초반에 이 이슈의 목표를 설정해서, 목표를 달성하면, 리뷰를 받고, 클로즈하는 쪽으로 진행해주세요. 👍
