### ISSUE TITLE
보영 - 선미에게 디자인  Asset 받아서 전체적으로 디자인 씌우기

### ISSUE THREAD

**Issue by fimuxd** [joeseonmi/SOS#28]

**Comment by joeseonmi** [comment]
셀은 말풍선처럼만드는건 테스트해보니까 잘됐어요
근데 실제로 우리가 만들때는 최소높이를 잘 정해줘야 하는 것 같아요.
테스트는 높이를 정해두고했는데 높이가 짧으니 안보이는거같아서 그건 데이터 뿌려보면서 
더 테스트해볼게여😢

**Comment by fimuxd** [comment]
완료
