### ISSUE TITLE
선미 - 파이어베이스를 이용한 데이터연동

### ISSUE THREAD

**Issue by joeseonmi** [joeseonmi/SOS#36]

**Comment by joeseonmi** [comment]
지금 파이어베이스로 여러작업 섞어서하고있는데요, 데이터도 뿌려보고있어요
근데 메인셀에 tag를 뿌릴때 어떻게 뿌려야할지가 문제가있네여
tag가 [String]인데 이걸 그대로 뿌리면
<img width="290" alt="2017-09-21 6 57 00" src="https://user-images.githubusercontent.com/28520065/30690399-1325fb80-9eff-11e7-9634-947d724cc1bc.png">
저런식으로 안이쁘게 뿌려지거든여😰

그래서 뿌릴때 "\(tagarray[0],tagarray[1],tagarray[2])" 머 이런식으로 뿌리면
예쁘게 뿌려지긴하는데 질문마다 tag의 갯수가 다르면 그게 또 문제가 될것같아서
어떤식으로 해결하는게 간단하고 쉬울지 곰인곰인중임니다😭

그리고 아직 파베가 서툴러서 Uid를 필터링해서 해당 Uid가있으면 데이터베이스에 새로 저장하지않는
예외처리를 아직 못하고있지만 조만간 고구마를 들들볶아서 해결하도록하겠슴니다

**Comment by joeseonmi** [comment]
그리고 th레드 문제도 있는것같은데 차차 공부하면서 해결해보도록하겠슴다@_@
다 테스트중이고 말끔히 끝난 내용이없기에(...) PR은 날리지않았어요🤢

**Comment by blackturtle2** [comment]
> tag가 [String]인데 이걸 그대로 뿌리면

이게 무슨 뜻인지 모르겠네요. 😥 

태그가 그래서 어렵긴 해요.
아직 태그를 터치할 수 있다거나 태그가 엄청 길다거나 하는 UI적 이슈는 없으니까, 고난이도는 아닐 것 같아요.
다만, 제한을 주는 건 나쁘지 않을 것 같긴 하네요.
예를 들어, 태그는 최대 5개이다.. 같은 제약 사항이 있어도 괜찮을 것 같습니당.
물론, 제약 사항이란 없는게 최고.. ~고구마를 볶아주세요(?!?!)~ =3=3=3 ㅋㅋㅋㅋㅋㅋㅋ


그리고 선미님, PR은 쏘지 않더라도 선미님 브랜치에 커밋은 해주세요. ~잦은 커밋 환영~
제가 브랜치 바꿔서 코드를 보려고 했는데, 커밋이 없으셔서.. 🤝

**Comment by joeseonmi** [comment]
코딩하다 맨날 빡종하다보니 커밋생각을 못했네여!!ㅋㅋㅋㅋㅋ오늘부턴 열심히 커밋할게요!!

**Comment by fimuxd** [comment]
해당부분 데이터 구조 변경하면서 해결되었음 `[String]` > `String`

지금은 예쁘게 잘 나옴

<img width="290" alt="screen shot 2017-09-29 at 11 29 05 pm" src="https://user-images.githubusercontent.com/27915244/31020453-03ab8240-a56e-11e7-9041-bbcde6aee3c0.png">
