### ISSUE TITLE
보영 - Favorite 관련 버그(?).

### ISSUE THREAD

**Issue by fimuxd** [joeseonmi/SOS#67]
1) 검색을 통해 Detail로 들어가서 좋아요를 한뒤 Main으로 돌아와 Favorite에 가보면 추가되어 있지 않음
 2) Main의 All 과 Favorite 세그를 번갈아 눌렀을 때 좋아요 카운트가 달라지는 문제

**Comment by fimuxd** [comment]
1. `BY_SearchPresentOverNavigationBarVC` 부분에 `UISearchControllerDelegate`를 사용해서 문제 해결

```swift
extension BY_SearchPresentOverNavigationBarViewController:UISearchControllerDelegate {
    
    func willDismissSearchController(_ searchController: UISearchController) {
        requestFavoriateQuestionData()
        tableView.reloadData()
    }
}
```

2. 문제 없는데 제가 착각한 것...ㅋㅋ

**Comment by blackturtle2** [comment]
> 문제 없는데 제가 착각한 것...ㅋㅋ

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
