### ISSUE TITLE
보영 - 콘텐츠 만들기

### ISSUE THREAD

**Issue by fimuxd** [joeseonmi/SOS#72]
매일 뭐 했는지 댓글 달기

**Comment by fimuxd** [comment]
**10월 11일** 

정말 미루고 미루다가 더 이상 미루면 안될 것 같아서 작성했습니다. 

1. 기존 작성했던 `ARC` 설명 수정 (사실상 다시 작성ㅋㅋ)
2. `MVC` / `RxSwift` / `AutoLayout` / `TDD` / `OOP` 에 대한 내용 작성. 
   - RxSwift 는 설명하는 것이 불가능하다 느꼈습니다... 엄청난 지식을 내포한 내용들이라.. ㅠㅠ
   - TDD: 이 것도 개념은 그렇구나 했는데 간단한 구현방법에서... 응? 간단히 구현이 안되는데? 하고 포기.....

**Comment by fimuxd** [comment]
@blackturtle2 
질문을 보며 공부하다 떠오른 것인데, 
`React Native` 와 `Android 와 iOS 차이점` 에 대한 질문이 좀 걸렸습니다.
`React Native`는 Swift에 대한 내용이 아닐 수 있고, 
`Android와 iOS 차이점` 은 매우 좋은 주제이지만, 저번에 Let'Swift에서, 앱에 Android 가 있어서 리젝되었다는 말이 기억나서...ㅋㅋㅋㅋㅋㅋㅋ
다른 주제로 교체하는 것은 어떨까요? 조심스럽게 건의합니당.

**Comment by blackturtle2** [comment]
제가 요 며칠 잠시 외도를 하느라(...), 콘텐츠 작성에 게으름을 피웠네요.
내일 빡세게 달려보겠습니다. 🙏 

아.. 확실히, `Android`라는 키워드가 들어가면 안되기는 하지요.
그럼, 이렇게 해보면 어떨까요. Android를 `aOS`로 표기해주세요. 👏 
사실 IT 현업에서는 Android라는 말이 기니까, aOS라고 쓰기도 하거든요.
그럼, 리뷰 검수에도 걸리는 것은 아니고.. 혹시나 걸리게 되면, `다른 OS`라고 표현해보죠. ~에헴~

~원래 리뷰는 5번 정도는 리젝 당하는 겁니다?~

**Comment by fimuxd** [comment]
ㅋㅋㅋㅋㅋㅋㅋ 그렇군요. 일단은 바꿔놓았습니다. 
~혹시 기분나빠할까바 iOS를 먼저 적음(쭈굴)~
![img_815c54eb12c6-1](https://user-images.githubusercontent.com/27915244/31701721-513672c4-b40d-11e7-8e23-316ce09cb0fd.jpeg)

++ `React Native` 에 대한 생각은 어떠신가요?

**Comment by blackturtle2** [comment]
iOS가 앞으로 오는거 💯 

`React Native`는 기술이니까요.
물론 페이스북이 만든 기술이기는 한데, 흠. 굳이 그렇게까지 터치를 할까 싶지만.. 일단, 이런건 애매모호하니, 리뷰를 넘겨보고, 뭐라고 하면 빼도록 해요. 😉
