### ISSUE TITLE
재성 - SOS, 테스트플라이트 올리기 ( 개발자계정에 앱 등록 )

### ISSUE THREAD

**Issue by blackturtle2** [joeseonmi/SOS#80]
다들 아시다시피, 금일 오후에 앱스토어 업로드 및 테스트 플라이트 실행에 성공하였습니다. ( 출시 X )

이제 출시를 코 앞에 두고, 콘텐츠 준비(.. 저도 죄송합.. :pray: )와 출시 준비물(스크린샷이라거나 앱 소개 텍스트라거나..)들이 필요합니다.

관련하여 구글 드라이브에 문서로 정리하였으니, 아래 링크를 참고해주세요.
https://docs.google.com/document/d/1zOUNS7oR9NlFJAVZeJX_bjNZ2FqMgts9lFRO8HzmOsM/edit?usp=sharing

**Comment by fimuxd** [comment]
자세한 설명 감사합니다

**Comment by blackturtle2** [comment]
클로즈합니다.
