### ISSUE TITLE
// 첫번째 Reject 대응

### ISSUE THREAD

**Issue by fimuxd** [joeseonmi/SOS#84]
재성님이 보내주신 애플의 Reject 메일을 자세히 읽어본 결과, 제가 이해한 내용은 다음과 같습니다.

### A. Reject 사유: 크게 2가지
- 첫번째: 
```
Specifically, the app did not respond when tapped various menus, except 개발자소개.
```
> `BY_MainTableViewController` 상의 햄버거 메뉴를 눌렀을 때, `개발자소개` 액션만 빼고는 무반응~인것처럼보이는~ 문제

- 두번째: 
```
Specifically, your app includes: 
- Apple trademark, Apple logo, imagery 
- or likeness 
- in the app and marketing screenshots.
```
> 애플 트레이드 마크를 너네가 감히 사용해?! 

### B. 문제 해결: 
다음과 같이 대응했으면 합니다. 
- 재성: 앱평가하기 기능 구현
~- 보영: 개발자초기화, 즐겨찾기 초기화 알람메시지 추가~ (완료)
~- 보영: 각 VC별 UIProgressView 또는 ActivityIndicator 추가~ (완료)
- 선미: 애플로고가 들어간 default 이미지 수정
- 선미: 네이버/구글링 했을 때 각각의 키워드로 검색되도록 할 것

**Comment by fimuxd** [comment]
### 보영: 개발자초기화, 즐겨찾기 초기화 알람메시지 추가
> ✅ 완료

- 즐겨찾기 초기화 알람
![simulator screen shot - iphone 6 plus - 2017-10-21 at 14 06 18](https://user-images.githubusercontent.com/27915244/31848263-0e7dc1ae-b669-11e7-80c8-4e9fa77ffebd.png)

- 캐릭터 설정 초기화 알람
![simulator screen shot - iphone 6 plus - 2017-10-21 at 14 06 22](https://user-images.githubusercontent.com/27915244/31848265-0f4e3a50-b669-11e7-9d1e-6df0651e3468.png)

**Comment by fimuxd** [comment]
### 보영: 각 VC별 UIProgressView 또는 ActivityIndicator 추가
> ✅완료
> - 별도로 뷰를 추가하는, ~지저분해지는 느낌~ 이 싫어서 NetworkActivityIndicator 를 추가하였습니다.

- 초기 구현시 메인테이블 뷰 뜨기 전
![simulator screen shot - iphone 6 plus - 2017-10-21 at 14 37 11](https://user-images.githubusercontent.com/27915244/31848435-d2618a52-b66d-11e7-8801-0378b719c5f7.png)

- `즐겨찾기 초기화`, `캐릭터 초기화`, 캐릭터별 답변, `좋아요` 누르고 취소할 때 등, Firebase Database와 통신하는 부분에 삽입했습니다.

**Comment by blackturtle2** [comment]
# 재성: 앱평가하기 기능 구현
 - 앱 내 앱스토어 리뷰 기능은 [iOS 10.3부터 지원되는 것](http://dev17.tistory.com/11)으로서 우리 쏘쓰에서는 앱스토어 이동 기능으로 구현하였습니다.
 - 코드는 매우 간단하고, 앱 아이디는 아이튠즈 커넥트에서 `앱 정보` > `Apple ID` 부분에 있습니다.
 - 관련 커밋: https://github.com/joeseonmi/SOS/commit/7e317c3349f12aba6fb69c126ee57955a3813265
 - 참고 링크: http://devsc.tistory.com/28

**Comment by fimuxd** [comment]
@blackturtle2 @joeseonmi 
모든 내용 업데이트 되었으므로 클로즈 합니다. 
우리, 프로젝트 팀 쏘쓰의 첫 App Store 출시를 자축합니다! 🎉🥂🍾
